export * from './pii/entity_vault';
export * from './pii/tier2_patterns';
export * from './trust/scorer';
export * from './trust/tier_classifier';
export * from './enrichment/l0_deterministic';
export * from './contact/matcher';
export * from './contact/attributor';
export * from './enrichment/event_extractor';
export * from './api/process';
export * from './auth/service_key';
export { BrainCoreClient } from './core_client/http';
export type { BrainCoreClientConfig } from './core_client/http';
export * from './guardian/silence';
export * from './llm/router';
export * from './staging/processor';
export * from './contact/alias';
export * from './scratchpad/lifecycle';
export * from './routing/task';
export * from './sync/engine';
export * from './embedding/generation';
export * from './mcp/delegation';
export { loadBrainConfig, validateBrainConfig } from './config/loading';
export type { BrainConfig } from './config/loading';
export * from './resilience/degradation';
export * from './crash/safety';
export * from './persona/registry';
export * from './vault_context/assembly';
export * from './pipeline/safety';
export * from './person/linking';
export * from './nudge/whisper';
